modify to add capability to read both Ginan and Bernese troposphere .…
GeoscienceAustralia/gnssanalysis pull request #34
Opened 2024-07-26 00:17 UTC by umma-zannat

to support both Ginan and Bernese tropospheric files (`.tro` files)

2024-07-26 00:19 UTC, ronaldmaj reviewed
Looks like some good changes coming in here to expand `.tro` reading 
- Do you have example `.tro` files we can test the new function on?

2024-07-26 00:30 UTC, umma-zannat commented
The other format for troposhere is `cost` file. `.tro` file is basically a sinex formatted file.

2024-07-26 00:31 UTC, umma-zannat commented
`    trop_sinex:                                 # Troposphere SINEX files are used to export troposhere products, such as ZTD and delay gradients
        output: true                           # Enable data exporting to troposphere SINEX file
        const_code:                                     # Troposphere SINEX const code
        directory:      "<OUTPUTS_ROOT>"                # Directory to export troposphere SINEX file
        filename:       "<CONFIG>-<LOGTIME>.tro" # Troposphere SINEX filename
        obs_code:       P                               # Troposphere SINEX observation code
        sol_type:       "Solution parameters"           # Troposphere SINEX solution type
        sources:        [KALMAN]                        # Source for troposphere delay data - KALMAN, etc
        version:        2                               # Troposphere SINEX version

    # log:`

2024-07-26 01:15 UTC, ronaldmaj requested changes
Again, looks good, couple docstrings that need to be finished off, but I think once you've got the unittests that Seb suggested in, this should be good to go

2024-07-26 01:15 UTC, ronaldmaj commented on gnssanalysis/gn_io/trop.py
> +    """For backwards compatibility"""
Docstring should be one-line sphinx (missing the description of input parameters, errors raise, what's returned, etc.: `:param` `:return`)
https://github.com/NilsJPWerner/autoDocstring/blob/master/docs/one-line-sphinx.md

2024-07-26 01:15 UTC, ronaldmaj commented on gnssanalysis/gn_io/trop.py
>      """Parses tro snx file into a dataframe.
One-line sphinx docstring (missing the description of input parameters, errors raise, what's returned, etc.: `:param` `:return`)

2024-07-26 05:30 UTC, ronaldmaj reviewed
Thanks heaps for putting through the `docstring` additions :pray: 

I've noticed you now have two `read_tro_solution` functions - is this intentional?
There is `_read_tro_solution` and `read_tro_solution`

2024-07-26 06:17 UTC, umma-zannat commented
`If no one uses the function with underscore I can delete it. I personally prefer not to use underscore. `

2024-07-29 01:28 UTC, ronaldmaj approved these changes
Unit tests are a great addition - can use that instead of testing manually. Happy for this to go in :+1:

2024-07-29 02:14 UTC, ronaldmaj commented on gnssanalysis/gn_io/trop.py
> +    """For backwards compatibility"""
This function is up for deletion if no one uses it (as there is the `read_tro_solution` function below this

2024-07-29 02:26 UTC, merged