SP3 clock normalisation
GeoscienceAustralia/gnssanalysis pull request #57
Opened 2024-09-19 00:56 UTC by EugeneDu-GA

Enable clock normalisation with sp3_difference

2024-09-20 05:11 UTC, ronaldmaj approved these changes
This looks good to me. I've done a check for other functions that call `gn_io.clk.sv_clocks` but I don't see anything else.
There is already a unit test for `compare_clk()` so that's covered, but I cannot say anything about `sp3_difference()` or `clk_difference()`. If it's working as expected for your purposes then I think that's fine.
I would look at putting through unit tests for these two functions (doesn't have to be in this PR)

2024-09-26 10:46 UTC, seballgeyer requested changes

2024-09-26 10:46 UTC, seballgeyer commented on gnssanalysis/gn_io/sp3.py
> +            b.loc[epoch].iloc[:, :3], hlm = hlm_trans(a.loc[epoch].EST[["X", "Y", "Z"]].values, b.loc[epoch].EST[["X", "Y", "Z"]].values)  # Eugene: hlm will be overwritten in the loop
I suppose you want hlm to be define first (before the if statement)
```python
hlm=[]
```
and in the for loop have:
```python
b.loc[epoch].iloc[:, :3], hlm_epoch = .... 
```
followed by 
```python
hlm.append(hlm_epoch)
```

2024-10-04 03:32 UTC, ronaldmaj approved these changes
As I said before, I think this is in a good enough state to go in, but I would wait on @seballgeyer to give his final approval before merging in

The one thing I would like to see is unit tests on functions that were touched here, but perhaps that could be done in a more wide-ranging PR that creates unit tests for a whole range of functions

2025-03-06 02:45 UTC, seballgeyer approved these changes

2025-03-06 02:46 UTC, merged