NPI-3655 Bring in remove_offline_sats(), add option to avoid crashing cubic interpolator when
GeoscienceAustralia/gnssanalysis pull request #61
Opened 2024-12-18 07:27 UTC by treefern

This PR brings in `remove_offline_sats()` from the other codebase, and adds options to `diff_sp3_rac()` to remove offline / partial nodata sats before running an SP3 diff. This is important because `NaN` / non-finite position data crashes the cubic interpolator used for velocity calculations.

A warning is now logged when using the cubic interpolator but **not** also enabling the option to remove offline sats.

2024-12-18 08:09 UTC, seballgeyer requested changes

2024-12-18 08:09 UTC, seballgeyer commented on gnssanalysis/gn_io/sp3.py
> +def remove_offline_sats(sp3_df: _pd.DataFrame):
Can we have an unit test on this one to make sure it works as expected?
Needs maybe 2 epochs, 2 satellite one with `0`.

2024-12-19 09:30 UTC, treefern commented
Further testing revealed this wasn't working as intended, due to only handling the raw representation of POS nodata, not handling `NaN`s. Updated.

2024-12-20 08:57 UTC, seballgeyer approved these changes
Looks good now. 
Did some very quick test.

2024-12-23 02:27 UTC, merged