NPI-3669 Migrate SP3 transform and trim, introduce minimal SP3 creation utility script
GeoscienceAustralia/gnssanalysis pull request #63
Opened 2024-12-23 06:21 UTC by treefern

Also adds an additional SP3 trimming option, on top of what existed in the original version.
The new utility script is primarily intended for making minimal SP3 files for unit tests.

Speaking of unit tests, tests for `filter_by_svs()` and `transform_sp3()` are yet to come.

2024-12-23 07:01 UTC, treefern commented
It turns out the approach taken to store the SV counts in the header, isn't currently compatible with the way we merge header attributes when combining DataFrames. This needs working through

2024-12-24 01:06 UTC, treefern commented
After this PR is merged, we should make another dev release (probably `57.dev4`), and update the downstream codebase in turn.

2025-01-06 01:27 UTC, ronaldmaj requested changes
As always, great PR. I've just chucked in a couple comments to extend the doc-strings for the new functions coming in. After that I think this is good to go in

2025-01-06 01:27 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +def filter_by_svs(
Very useful function and I've tested it now on a sample SP3 file - works great!

2025-01-06 01:27 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    """
doc-string needs to be extended to describe parameters

2025-01-06 01:27 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    """
doc-string needs to be extended to describe parameters

2025-01-06 01:27 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    """
doc-string needs to be extended to describe parameters

2025-01-06 01:27 UTC, ronaldmaj commented on gnssanalysis/test_file_creation_util.py
> +####
Unfinished comments? Or separating one section from another?

2025-01-07 23:04 UTC, ronaldmaj requested changes
Just a couple minor things to fix up with docStrings

2025-01-07 23:04 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    :param DataFrame sp3_df: The input SP3 DataFrame.
As with `filter_by_svs()` above, this will need to be: `_pd.DataFrame` rather than just `Dataframe`

2025-01-07 23:04 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
>       :param DataFrame a: The sp3_a DataFrame.
`DataFrame` --> `_pd.DataFrame`

2025-01-07 23:04 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
>       :param DataFrame b : The sp3_b DataFrame.
`DataFrame` --> `_pd.DataFrame`

2025-01-07 23:04 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    :return tuple[pandas.DataFrame, list]: A tuple containing the updated sp3_b DataFrame and the HLM array with applied computed parameters and residuals.
`pandas.DataFrame` --> `_pd.DataFrame`

2025-01-07 23:04 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    :return DataFrame: The DataFrame containing the difference in RAC coordinates.
`DataFrame` --> `_pd.DataFrame`

2025-01-07 23:51 UTC, treefern commented on gnssanalysis/gn_io/sp3.py
>       :param DataFrame a: The sp3_a DataFrame.
Ah, I changed this one to be more generic because that seemed more readable (given the renamed import is an internal thing). If it's parsed by an IDE I can see that backfiring.

2025-01-08 00:00 UTC, treefern commented on gnssanalysis/gn_io/sp3.py
>       :param DataFrame a: The sp3_a DataFrame.
In other parts of the code, we have `pandas.DataFrame`. We should standardise on one format for docstrings. One of:
- `DataFrame`
- `pandas.DataFrame`
- `_pd.DataFrame` (looks non-standard for human use but may have the benefit of being resolvable in our context by an IDE.)

2025-01-08 02:28 UTC, treefern commented on gnssanalysis/gn_io/sp3.py
>       :param DataFrame a: The sp3_a DataFrame.
These have now been updated to fit the convention applied to the majority of code in this codebase, which is using the imported module name, e.g. `_pd.DataFrame`

2025-01-08 03:29 UTC, ronaldmaj approved these changes
Awesome, thanks for pushing those changes through - I think it is good to go in now 👍

2025-01-08 03:29 UTC, merged