NPI-3668 SP3 header stated values vs content checks, and ORB_TYPE update on performing Helmert transformation
GeoscienceAustralia/gnssanalysis pull request #64
Opened 2024-12-23 06:29 UTC by treefern

This PR is intended to add a bit more robustness to our generated SP3 headers.

This adds:
- Checks that the list of SVs the header claims the SP3 data contains, match the values in the DataFrame itself (which will become the content of the SP3 file written out).
- Logic to set the `ORB_TYPE` field of the SP3 header to `HLM`, when a Helmert transformation is performed on the SP3 DataFrame. This is done to keep the header metadata used to write out headers, more consistent with changes made to the data itself.

2025-01-06 00:50 UTC, ronaldmaj requested changes
This is a great addition and something we've discussed so generally I'm happy with how this has turned out. 
My one suggestion is to include a test for a file / header where the number of satellites is not correct - make sure the error flags as expected. 
I think just a small header should be enough, one where the number in the header is wrong. Then you can pass that bytes object through to `parse_sp3_header`.

2025-01-06 00:50 UTC, ronaldmaj commented on tests/test_sp3.py
> +        self.assertEqual(
This is a nice test to see that the feature works as intended for a normal file, but it would be good to write one up to check that it also works for a corrupted file / header (i.e. get the error to flag as expected)

2025-01-06 00:50 UTC, ronaldmaj commented on gnssanalysis/gn_io/sp3.py
> +    b.attrs["HEADER"].head.ORB_TYPE = "HLM"  # Update b's header to reflect Helmert transformation has been applied
This is a good addition to ensure we are conveying accurate information

2025-01-09 13:13 UTC, treefern commented
Added some additional consistency check logic to `read_sp3()`.
In particular new consistency checks on the number of epochs given by the filename / header / content, plus an initial unit test for this (should be extended with more cases and a success example).

2025-01-10 05:55 UTC, ronaldmaj approved these changes
Happy for this to go in - unit-test to check an sp3 block with incorrect number of SVs is now in the code

2025-01-10 05:55 UTC, merged